Complete rewrite for better modularity and support any backup tool

diff --git a/common/cronjob.yml b/common/cronjob.yml
--- a/common/cronjob.yml
+++ b/common/cronjob.yml
@@ -1,79 +1,62 @@
 kind: CronJob
 apiVersion: batch/v1
 metadata:
-  name: rustic-k8s-backup-cron-job
+  name: k8s-simple-backup-cron-job
 spec:
-  schedule: 0 0 * * *  # Default to every day at 0:00 AM UTC
+  schedule: 3 0 * * *  # Default to every day at 3:00 AM UTC
   timeZone: UTC
   concurrencyPolicy: Forbid
   jobTemplate:
     spec:
       template:
         spec:
-          serviceAccountName: rustic-k8s-backup-service-account
+          serviceAccountName: k8s-simple-backup-service-account
           restartPolicy: Never
-          containers:
-            - name: flux-k8s-backup
-              image: yeicor/rustic:main
+          initContainers:
+            - name: k8s-simple-backup-downscale
+              image: bitnami/kubectl:latest
               command:
                 - /bin/sh
                 - -c
                 - |
-                  set -ex
-
-                  if [ ! -z "${resource_kind}" ]; then
-                    echo "Installing kubectl to manage the ${resource_kind}/${resource_name} in the ${namespace:-default} namespace"
-                    curl -L -o /tmp/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-                    chmod +x /tmp/kubectl
-                    prev_replicas=$(/tmp/kubectl get ${resource_kind} -n ${namespace:-default} ${resource_name} -o jsonpath='{.spec.replicas}')
-                    echo "- The previous number of replicas was ${prev_replicas}, scaling down to 0 for backup..."
-                    /tmp/kubectl scale ${resource_kind} -n ${namespace:-default} ${resource_name} --replicas=0
-                    while [ "$(/tmp/kubectl get ${resource_kind} -n ${namespace:-default} ${resource_name} -o jsonpath='{.status.availableReplicas}')" -ne "0" ]; do
-                      echo "Waiting for ${resource_kind}/${resource_name} to scale down to 0 available replicas..."
-                      sleep 5
-                    done
-                  else
-                    echo "No resource configured to scale down for backup. This is not recommended."
+                  if [ -z "$resource_kind" ] || [ -z "$resource_name" ] || [ -z "$namespace" ]; then
+                    echo "Backing up this persistent volume without scaling down any resource."
+                    exit 0
                   fi
-
-                  echo "Running the backup command..."
-                  [ -d /data ] && cd /data
-                  # rustic -P rustic-base -P rustic show-config  # WARNING: Shows the password in the logs!
-                  rustic -P rustic-base -P rustic ${rustic_cmd} | tee /tmp/backup.log
-
-                  # Rustic does not set exit codes, so grep for errors... https://github.com/rustic-rs/rustic/issues/927
-                  if grep -i -q "ERROR" /tmp/backup.log; then
-                    echo "Backup failed! Exiting..."
+                  kubectl get -n $namespace $resource_kind/$resource_name -o jsonpath='{.spec.replicas}' > /tmp/replicas
+                  kubectl scale -n $namespace $resource_kind/$resource_name --replicas=0
+                  ok="0"
+                  for i in $(seq 1 $scale_down_timeout); do
+                    if [ "$(kubectl get -n $namespace $resource_kind/$resource_name -o jsonpath='{.status.availableReplicas}')" -eq "0" ]; then
+                      ok="1"
+                      break
+                    fi
+                    echo "Waiting for $resource_kind/$resource_name to scale down to 0 available replicas..."
+                    sleep 1
+                  done
+                  if [ "$ok" -ne "1" ]; then
+                    echo "ERROR: The $resource_kind/$resource_name did not scale down to 0 replicas."
                     exit 1
                   fi
-
-                  if [ ! -z "${resource_kind}" ]; then
-                    echo "Backup successful! Scaling back ${resource_kind}/${resource_name} to ${prev_replicas} replicas..."
-                    cur_replicas=$(/tmp/kubectl get ${resource_kind} -n ${namespace:-default} ${resource_name} -o jsonpath='{.spec.replicas}')
-                    if [ "${cur_replicas}" -ne "0" ]; then
-                      echo "WARNING: The ${resource_kind}/${resource_name} is not currently scaled down to 0 replicas. Data may be corrupted!"
-                    fi
-                    /tmp/kubectl scale ${resource_kind} -n ${namespace:-default} ${resource_name} --replicas=${prev_replicas}
-                    while [ "$(/tmp/kubectl get ${resource_kind} -n ${namespace:-default} ${resource_name} -o jsonpath='{.status.availableReplicas}')" -ne "${prev_replicas}" ]; do
-                      echo "Waiting for ${resource_kind}/${resource_name} to scale up to ${prev_replicas} available replicas..."
-                      sleep 5
-                    done
-                  fi
-              volumeMounts:
-                - mountPath: /data
-                  name: data
-                - mountPath: /etc/rustic/
-                  name: config
-                - mountPath: /tmp
-                  name: tmp
-              envFrom:
-                - secretRef:
-                    name: rustic-secret-env
-                    optional: true
+              env:
+                - name: resource_kind
+                  value: ""
+                - name: resource_name
+                  value: ""
+                - name: namespace
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: metadata.namespace
+                - name: scale_down_timeout
+                  value: "30"
+              envFrom: &envFrom
                 - configMapRef:
-                    name: rustic-configmap-env
+                    name: k8s-simple-backup-configmap-env
                     optional: true
-              securityContext:
+                - secretRef: # Can override the configMap values
+                    name: k8s-simple-backup-secret-env
+                    optional: true
+              securityContext: &securityContext
                 allowPrivilegeEscalation: false
                 capabilities:
                   drop:
@@ -84,13 +67,85 @@ spec:
                 runAsNonRoot: true
                 runAsUser: 1000
                 runAsGroup: 1000
+              volumeMounts: &volumeMountsKubectl
+                - mountPath: /tmp
+                  name: tmp
+
+            - name: k8s-simple-backup
+              image: pschiffe/borg:latest
+              volumeMounts:
+                - mountPath: /data
+                  name: data
+                  readOnly: true
+                - mountPath: /tmp
+                  name: tmp
+              env: &envCommon
+                - name: resource_kind
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: spec.initContainers[0].env[0].value
+                - name: resource_name
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: spec.initContainers[0].env[1].value
+                - name: namespace
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: spec.initContainers[0].env[2].value
+                - name: scale_up_timeout
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: spec.initContainers[0].env[3].value
+                - name: pvc_name
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: spec.jobTemplate.spec.template.spec.volumes[0].persistentVolumeClaim.claimName
+                - name: ARCHIVE
+                  value: "$(namespace)-$(resource_kind)-$(resource_name)-$(pvc_name)-$(date +'%Y-%m-%d-%H-%M-%S')"
+              envFrom: *envFrom
+              securityContext: *securityContext
+
+          containers: # At least one container is required
+            - name: k8s-simple-backup-upscale
+              image: bitnami/kubectl:latest
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  if [ -z "$resource_kind" ] || [ -z "$resource_name" ] || [ -z "$namespace" ]; then
+                    echo "Backing up this persistent volume without scaling down any resource."
+                    exit 0
+                  fi
+                  cur_replicas=$(kubectl get -n $namespace $resource_kind/$resource_name -o jsonpath='{.spec.replicas}')
+                  if [ "$cur_replicas" -ne "0" ]; then
+                    echo "ERROR: The $resource_kind/$resource_name did not stay scaled down to 0 replicas."
+                    echo "       Data may be corrupted!" 
+                    echo "Check that your controllers do not automatically scale up the replicas while the backup is running."
+                    exit 1
+                  fi
+                  replicas_to_restore=$(cat /tmp/replicas)
+                  kubectl scale -n $namespace $resource_kind/$resource_name --replicas=$replicas_to_restore
+                  ok="0"
+                  for i in $(seq 1 $scale_up_timeout); do
+                    if [ "$(kubectl get -n $namespace $resource_kind/$resource_name -o jsonpath='{.status.availableReplicas}')" -eq "$replicas_to_restore" ]; then
+                      ok="1"
+                      break
+                    fi
+                    echo "Waiting for $resource_kind/$resource_name to scale up to $replicas_to_restore available replicas..."
+                    sleep 1
+                  done
+                  if [ "$ok" -ne "1" ]; then
+                      echo "ERROR: The $resource_kind/$resource_name did not scale up to $replicas_to_restore replicas."
+                      exit 1
+                  fi
+              env: *envCommon
+              envFrom: *envFrom
+              volumeMounts: *volumeMountsKubectl
+              securityContext: *securityContext
           volumes:
             - name: data
               persistentVolumeClaim:
                 # readOnly: true  # May need to write for restore commands
                 claimName: YOU_MUST_OVERRIDE_THE_claimName_VALUE  # Replace using Kustomize patches
-            - name: config
-              configMap:
-                name: rustic-configmap
             - name: tmp
               emptyDir: { }
